feed/urls.py
from django.urls import path
from .views import HomePageView, PostDetailView, AddPostView

app_name = 'feed'

urlpatterns = [
    path('', HomePageView.as_view(), name='index'),
    path('detail/<int:pk>/', PostDetailView.as_view(), name='detail'),
    path('post/', AddPostView.as_view(), name='post')
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from feed import urls as feed_urls 
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(feed_urls,namespace='feed'),)
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

feed/models.py
from django.db import models
from sorl.thumbnail import ImageField

# Create your models here.
class Post(models.Model):
    text = models.CharField(max_length=140, blank=False, null=False)
    image = ImageField ()

    def __str__(self):
        return self.text
        

feed/forms.py
from django import forms

class PostForm(forms.Form):
    text = forms.CharField()
    image = forms.FileField()

feed/views.py
from django import http
from django.contrib import messages
from typing import Any, Dict
from django.http import HttpResponse
from django.views.generic import TemplateView, DetailView, FormView
from .forms import PostForm
from .models import Post

class HomePageView(TemplateView):
    template_name = "home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context ['posts'] = Post.objects.all().order_by('-id')
        #context ['my_thing'] = "Hello World :p this is dynamic"
        """context = {
            'my_thing': 'Hello World from Dudley'
        }"""
        return context
    
class PostDetailView(DetailView):
    template_name = "detail.html"
    model = Post

class AddPostView(FormView):
    template_name = "new_post.html"
    form_class = PostForm
    success_url = "/"

    def dispatch(self, request, *args: Any, **kwargs):
        self.request = request
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        new_object = Post.objects.create(
            text = form.cleaned_data['text'],
            image = form.cleaned_data['image'],
        )
        messages.add_message(self.request, messages.SUCCESS, 'Your post was successful')
        return super().form_valid(form)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} Document {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

</head>
<body>
    {% include "includes/navbar.html" %}
    {% if messages %}
        {% for message in messages %}
            <div class="bg-{% if message.tags %}{{ message.tags }}{% else %}success{% endif %}
            bg-gradient text-center text-white py-4">
                    {{ message }}
            </div>    
        {% endfor %}
    {% endif %}
    
    

    <div class= "container" >
        {% block body %} {% endblock %}
    </div>     
   
    
</body>
</html>

templates/detail.html
{% extends "base.html" %}

{% block <title>detail</title> %} {% endblock %}

{% block body %}
<div class="row">
    <h1> {{ object.text }}</h1>
    <img src="{{ object.image.url }}" class="img-fluid my-5 rounded" style="width: 300px; height: 500px; display: flexbox;">
</div>
{% endblock %}

templates/home.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %} Home {% endblock %}
{% block body %}

<div class="row">
    {% for post in posts %}
          <div class="col-sm-6 col-md-4">
          <div class="card" style="width: 18rem;">
               {% thumbnail post.image "200x200" crop="top" as im %}
                    <img src="{{ im.url }}" class="card-img-top" alt="...">
               {% endthumbnail %}  
               <div class="card-body">
                    <h5 class="card-title">{{ post.text }}</h5>
                    <!--p class="card-text">{{ post.text }}</p -->
                    <a href="{% url 'feed:detail' post.id %}" class="btn btn-primary">View Detail</a>
               </div>
          </div>
     </div>
     {% empty %}
     <div class="col-sm-6 offset-3 text-center py-5 my-5">
         <h1>Welcome!</h1>
         <p>Add your first image?</p>
         <a href="{% url 'feed:post' %}" class="btn btn-lg btn-success">Upload Image</a>
     </div>
     {% endfor %}
</div>     
       
   
{% endblock %}

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
    <a class="navbar-brand" href="/">Image Share</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'feed:index' %}">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'feed:post' %}">Add Post</a>
        </li>
        
        </ul>
    </div>
    </div>
</nav>

templates/new_post.html
{% extends "base.html" %}

{% block title %} Upload Form {% endblock %}
{% block body %}
    <form method="POST" action="" enctype="multipart/form-data" class="col-sm-4 offset-4 py-5 my-5">
        <h1> <strong>Upload Image!</strong></h1>
        {%csrf_token%}
       
       <div>
            {{ form.as_p}}
       </div> 
       <div>
            <ul>
                
                <button type="submit" class="btn btn-primary">
                     Upload form
                </button>
                
                <button class="btn btn-warning"><a href="{% url 'feed:index' %}">&lAarr; Cancel </a></button>
                    
            </ul>
       </div> 
    </form>
       
    
{% endblock %}